// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqDIadW3W1mH1GzU8yU8xwXaJCMoojsGE',
    appId: '1:219440040411:web:8ba8af2bbe567d8f73fffe',
    messagingSenderId: '219440040411',
    projectId: 'digi-roloscan',
    authDomain: 'digi-roloscan.firebaseapp.com',
    storageBucket: 'digi-roloscan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5iLX8-8dqb12zbvcvPleh1pwIsuBTDzs',
    appId: '1:219440040411:android:70ec773e587e3cb273fffe',
    messagingSenderId: '219440040411',
    projectId: 'digi-roloscan',
    storageBucket: 'digi-roloscan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtTZMsuhzqhRoT1lXkn4Q6oHdZe_Zrybs',
    appId: '1:219440040411:ios:a4eb76340745fecd73fffe',
    messagingSenderId: '219440040411',
    projectId: 'digi-roloscan',
    storageBucket: 'digi-roloscan.firebasestorage.app',
    iosBundleId: 'com.example.roloDigiCard',
  );
}
